apiVersion: v1
kind: ConfigMap
metadata:
  name: spring-boot-config
  namespace: app
data:
  SPRING_CONFIG_NAME: application-dev
  DB_PORT: "3306"
  DB_NAME: ziplinedb
  DB_USERNAME: root
  REDIS_PORT: "6379"
  REDIS_TIMEOUT: "2000"
  PORT_API: "8080"
  MAX_HTTP_TOMCAT_FORM_POST_SIZE: 10MB
  AWS_REGION: ap-northeast-2
  AWS_STACK_VAL: "false"
  SURVEY_DELIMITER: $$###
  FILE_ALLOWED_MEME_TYPES: image/jpg,image/jpeg,image/png,image/webp,application/pdf,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet,application/vnd.ms-excel,text/csv,
    application/csv,
    text/plain,application/x-tika-ooxml