spring:
  datasource:
    url: jdbc:mariadb://${DB_URL}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: true
  data:
    redis:
      host: ${REDIS_URL}
      port: ${REDIS_PORT}
      timeout: ${REDIS_TIMEOUT}
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  cache:
    type: redis
  session:
    redis:
      namespace: ${REDIS_SESSION_NAMESPACE}
      flush-mode: ${SESSION_FLUSH_MODE}
    timeout: ${SESSION_TIMEOUT}
server:
  port: ${PORT_API}
  tomcat:
    max-http-form-post-size: ${MAX_HTTP_TOMCAT_FORM_POST_SIZE}
aws:
  region: ${AWS_REGION}
  credentials:
    access-key: ${AWS_ACC_KEY}
    secret-key: ${AWS_SEC_KEY}
  s3:
    bucket: ${AWS_S3_BUCKET}
cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS_DEV}
sms:
  api-key: ${SMS_API_KEY}
  secret-key: ${SMS_SEC_KEY}
  auth-method: ${SMS_AUTH_METHOD}
  fromNumber: ${SMS_FROM_NUMBER}
cloud:
  aws:
    stack:
      auto: ${AWS_STACK_VAL}
survey:
  questionUid-delimiter: ${SURVEY_DELIMITER}
file:
  allowed-mime-types: ${FILE_ALLOWED_MEME_TYPES}
cache:
  keys:
    children-regions-prefix: ${CACHE_KEY_CHILDREN_REGIONS_PREFIX}
kakao:
  api:
    key: ${KAKAO_API_KEY}
management:
  metrics:
    distribution:
      percentiles:
        http.server.requests: 0.5, 0.9, 0.95, 0.99
      percentiles-histogram:
        http.server.requests: true
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    metrics:
      access: unrestricted
  prometheus:
    metrics:
      export:
        enabled: true
  newrelic:
    metrics:
      export:
        account-id: ${NR_ACCOUNT_ID}
        enabled: true
        api-key: ${NR_API_KEY}