name: SonarQube Analysis

on:
  workflow_run:
    workflows: ["Test and Local Build"]
    types:
      - completed

jobs:
  sonar:
    name: SonarQube Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache SonarQube packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Build and Analyze with SonarQube
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: |
          ./gradlew build sonar --info

      - name: Send SonarQube Result to Slack
        uses: rtCamp/action-slack-notify@v2
        env:
            SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
            SLACK_MESSAGE: "SonarQube 분석 완료! 결과를 확인하세요: ${{ secrets.SONAR_HOST_URL }}/dashboard?id=zipline-j"